/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List currently-active sessions. */
        get: operations["listSessions"];
        put?: never;
        /** Create a new session backed by a fresh ANDES worker subprocess. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe a session. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** Close a session and reap its worker subprocess. */
        delete: operations["closeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load an ANDES case file (with optional addfiles) into a session. */
        post: operations["loadCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current topology view of a session's loaded case. */
        get: operations["getTopology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-load the current case to return to pre-setup state.
         * @description Calls ``andes.load(setup=False)`` again. **Cost is honest** — this is
         *     a full re-parse, not a fast path. Documented in the OpenAPI summary so
         *     callers can budget for multi-second latency on large cases.
         */
        post: operations["reloadCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/pflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run power flow on the session's loaded case. */
        post: operations["runPflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/disturbances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register one or more disturbances on a pre-setup session. */
        post: operations["addDisturbances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topology/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-model parameter metadata for the add/edit forms.
         * @description Static endpoint — the schema mirrors a compile-time table on the
         *     wrapper. Auth-gated only because the rest of the substrate is.
         */
        get: operations["getTopologySchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/elements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a topology element to a pre-setup session. */
        post: operations["addElement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/elements/{model}/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit parameters on an existing pre-setup element. */
        put: operations["editElement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/blank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an empty andes.System() for a session. */
        post: operations["createBlankSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/tds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a time-domain simulation (batch mode; streaming lands in Unit 6). */
        post: operations["runTds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported case files in the workspace root.
         * @description Return a sorted list of files in the workspace root whose extension
         *     matches the supported set. Non-recursive in v0.1; excludes hidden files
         *     and symlinks.
         */
        get: operations["listWorkspaceFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the SLD layout sidecar JSON adjacent to a case file. */
        get: operations["getWorkspaceLayout"];
        /** Write the SLD layout sidecar JSON adjacent to a case file. */
        put: operations["putWorkspaceLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddDisturbancesRequest
         * @description Request body for ``POST /sessions/{id}/disturbances``.
         *
         *     Accepts a list so a caller can register multiple disturbances in one
         *     request — useful for the v0.2 timeline editor that wants to commit a
         *     full study scenario at once. ANDES rejects all post-setup ``add()`` calls,
         *     so this endpoint is gated on pre-setup state (returns 409 otherwise with
         *     a hint to call ``/reload``).
         */
        AddDisturbancesRequest: {
            /**
             * Disturbances
             * @description List of disturbance specifications. Discriminated by the ``kind`` field (``fault``, ``toggle``, ``alter``).
             */
            disturbances: (components["schemas"]["FaultSpec"] | components["schemas"]["ToggleSpec"] | components["schemas"]["AlterSpec"])[];
        };
        /**
         * AddDisturbancesResponse
         * @description Response body for ``POST /sessions/{id}/disturbances``.
         */
        AddDisturbancesResponse: {
            /**
             * Accepted
             * @description One ack entry per accepted disturbance, in input order.
             */
            accepted: components["schemas"]["DisturbanceAck"][];
        };
        /**
         * AddElementRequest
         * @description Request body for ``POST /sessions/{id}/elements``.
         *
         *     Adds a single topology element (Bus, Line, generator, load, shunt) to a
         *     pre-setup System. The wrapper validates the model name + param keys
         *     against an internal whitelist BEFORE invoking ANDES; unknown keys
         *     surface as 422 ``ProblemDetails`` listing both the rejected and the
         *     allowed sets.
         */
        AddElementRequest: {
            /**
             * Model
             * @description ANDES model class name. Supported in v0.1.x: ``Bus``, ``Line``, ``PV``, ``Slack``, ``GENROU``, ``GENCLS``, ``PQ``, ``ZIP``, ``Shunt``. Unknown models are rejected with 422.
             */
            model: string;
            /**
             * Params
             * @description Flat dict of model parameters. Keys are validated against the per-model whitelist; values pass through to ``ss.add()``. Required keys vary per model — query ``GET /api/topology/schema`` for the live form metadata.
             */
            params: {
                [key: string]: number | string | boolean;
            };
        };
        /**
         * AlterSpec
         * @description Parameter alteration at a scheduled time — used for load steps,
         *     parameter ramps, set-point changes, etc.
         *
         *     Maps to ``ss.add('Alter', model=..., dev=..., src=..., t=..., value=...)``.
         */
        AlterSpec: {
            /**
             * Kind
             * @description Discriminator: this spec creates an ANDES Alter device.
             * @default alter
             * @constant
             */
            kind: "alter";
            /**
             * Model
             * @description ANDES model class name containing the parameter.
             */
            model: string;
            /**
             * Dev Idx
             * @description ANDES idx of the device within ``model``.
             */
            dev_idx: number | string;
            /**
             * Src
             * @description Source parameter name on the model (e.g., 'p0' for active-power set-point on a generator).
             */
            src: string;
            /**
             * T
             * @description Time the parameter change applies, in seconds.
             */
            t: number;
            /**
             * Value
             * @description New value of the parameter at time ``t``.
             */
            value: number;
        };
        /**
         * BlankSystemResponse
         * @description Response body for ``POST /sessions/{id}/blank`` (201).
         *
         *     Returns the empty topology so the client immediately switches to the
         *     blank-system rendering path (centered ``Add your first bus`` prompt).
         */
        BlankSystemResponse: {
            /** @description Empty topology snapshot for the freshly-created blank System. All buckets are empty; ``state`` is ``pre-setup``. */
            topology: components["schemas"]["TopologySummary"];
        };
        /**
         * BusCoord
         * @description One bus's 2D coordinate in the layout sidecar.
         *
         *     Coordinates are in arbitrary canvas units; the UI rescales them at render
         *     time. Infinity / NaN are rejected at validation time.
         */
        BusCoord: {
            /**
             * X
             * @description Bus X coordinate, finite (no NaN/Inf).
             */
            x: number;
            /**
             * Y
             * @description Bus Y coordinate, finite (no NaN/Inf).
             */
            y: number;
        };
        /**
         * DisturbanceAck
         * @description One entry in the response to ``POST /sessions/{id}/disturbances``.
         */
        DisturbanceAck: {
            /**
             * Kind
             * @description Discriminator from the original spec.
             * @enum {string}
             */
            kind: "fault" | "toggle" | "alter";
            /**
             * Idx
             * @description ANDES idx assigned to the created disturbance device. Use this to reference the disturbance in subsequent operations.
             */
            idx: number | string;
        };
        /**
         * EditElementRequest
         * @description Request body for ``PUT /sessions/{id}/elements/{model}/{idx}``.
         *
         *     Updates one or more parameters on an existing element. The same
         *     pre-setup gate + whitelist as ``AddElementRequest`` apply. ``idx`` and
         *     ``name`` cannot be edited (they would desync ANDES's internal indexes);
         *     create a new element if you need to reassign topology references.
         */
        EditElementRequest: {
            /**
             * Params
             * @description Subset of model parameters to overwrite. Each key must be in the per-model whitelist; ``idx`` / ``name`` are explicitly rejected (create a new element instead).
             */
            params: {
                [key: string]: number | string | boolean;
            };
        };
        /**
         * ElementCreated
         * @description Response body for ``POST /sessions/{id}/elements`` (201).
         *
         *     Carries the newly-built ``TopologyEntry`` so the client can update its
         *     cache without re-fetching the full topology. Web-side mutation hooks
         *     use this to optimistically update bus dropdowns before the topology
         *     re-fetch resolves.
         */
        ElementCreated: {
            /** @description The element that was just added, with its assigned idx + the parameters as ANDES read them back. */
            element: components["schemas"]["TopologyEntry"];
        };
        /**
         * FaultSpec
         * @description 3-phase-to-ground fault on a bus.
         *
         *     Maps to ``ss.add('Fault', bus=..., tf=..., tc=..., xf=..., rf=...)``.
         *     Single-phase faults are not natively supported by ANDES and are not in
         *     scope (per Phase A plan).
         */
        FaultSpec: {
            /**
             * Kind
             * @description Discriminator: this spec creates an ANDES Fault device.
             * @default fault
             * @constant
             */
            kind: "fault";
            /**
             * Bus Idx
             * @description ANDES idx of the bus where the fault is applied.
             */
            bus_idx: number | string;
            /**
             * Tf
             * @description Time the fault is applied, in seconds.
             */
            tf: number;
            /**
             * Tc
             * @description Time the fault is cleared, in seconds. Must be > tf.
             */
            tc: number;
            /**
             * Xf
             * @description Fault reactance in pu.
             * @default 0.0001
             */
            xf: number;
            /**
             * Rf
             * @description Fault resistance in pu.
             * @default 0
             */
            rf: number;
        };
        /**
         * GeneratorOutput
         * @description Per-generator PF output. Active + reactive injection at the
         *     generator's terminal bus, plus the terminal voltage (pu).
         */
        GeneratorOutput: {
            /**
             * P
             * @description Active power generated at the terminal bus, in MW.
             */
            p: number;
            /**
             * Q
             * @description Reactive power generated at the terminal bus, in MVAr.
             */
            q: number;
            /**
             * V
             * @description Terminal bus voltage magnitude (pu).
             */
            v: number;
            /**
             * Bus
             * @description Terminal bus idx.
             */
            bus: number | string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LineFlow
         * @description Per-line active and reactive power flow, measured at terminal 1
         *     (``bus1``) flowing into the line toward terminal 2 (``bus2``).
         *
         *     Sign convention: positive ``p`` means real power flowing FROM ``bus1``
         *     INTO the line; positive ``q`` means reactive power flowing FROM ``bus1``
         *     INTO the line. The v0.1 SLD overlay uses the sign of ``p`` to render
         *     directional arrows along each branch.
         */
        LineFlow: {
            /**
             * P
             * @description Active power leaving ``bus1`` into the line, in MW (i.e., computed in pu and multiplied by the system base MVA).
             */
            p: number;
            /**
             * Q
             * @description Reactive power leaving ``bus1`` into the line, in MVAr.
             */
            q: number;
            /**
             * From Idx
             * @description ANDES idx of the ``bus1`` terminal (the from-side bus).
             */
            from_idx: number | string;
            /**
             * To Idx
             * @description ANDES idx of the ``bus2`` terminal (the to-side bus).
             */
            to_idx: number | string;
        };
        /**
         * LoadCaseRequest
         * @description Request body for ``POST /sessions/{id}/case``. All paths are
         *     workspace-relative; the substrate canonicalizes them with O_NOFOLLOW
         *     before passing to ANDES.
         */
        LoadCaseRequest: {
            /**
             * Primary Path
             * @description Workspace-relative path to the primary case file. Supported formats: xlsx, raw, dyr, json, m. The substrate routes through ANDES's native readers; format is detected from the extension.
             */
            primary_path: string;
            /**
             * Addfiles
             * @description Optional list of workspace-relative addfile paths. PSS/E .raw (steady-state) and .dyr (dynamics) are paired via this mechanism; pass [.dyr path] when loading a .raw.
             */
            addfiles?: string[] | null;
        };
        /**
         * LoadConsumption
         * @description Per-load PF consumption at the converged voltage.
         */
        LoadConsumption: {
            /**
             * P
             * @description Active power drawn, in MW.
             */
            p: number;
            /**
             * Q
             * @description Reactive power drawn, in MVAr.
             */
            q: number;
            /**
             * Bus
             * @description Terminal bus idx.
             */
            bus: number | string;
        };
        /**
         * PflowResult
         * @description Power-flow run result. Bus voltages and angles are keyed by ANDES idx.
         */
        PflowResult: {
            /**
             * Run Id
             * @description Server-generated identifier for this PF run. Use it with GET /sessions/{id}/pflow/{run_id} to fetch the result later.
             */
            run_id: string;
            /**
             * Converged
             * @description ``true`` if PF converged within the iteration limit. Non-convergence is NOT a server error; it is a valid power-system outcome the caller must handle.
             */
            converged: boolean;
            /**
             * Iterations
             * @description Number of Newton-Raphson iterations executed.
             */
            iterations: number;
            /**
             * Mismatch
             * @description Final mismatch (max element of the residual vector) at the converged solution. For non-converged runs this is the last iteration's mismatch.
             */
            mismatch: number;
            /**
             * Bus Voltages
             * @description Bus voltage magnitudes (pu) keyed by ANDES idx (stringified). JSON object keys must be strings; the ANDES idx is converted at the boundary.
             */
            bus_voltages: {
                [key: string]: number;
            };
            /**
             * Bus Angles
             * @description Bus voltage angles (radians) keyed by ANDES idx (stringified).
             */
            bus_angles: {
                [key: string]: number;
            };
            /**
             * Line Flows
             * @description Per-line P/Q flow at terminal 1, keyed by line idx (stringified). Empty if the wrapper could not extract line flows from the post-PF System (e.g., on an unexpected ANDES API change). Populated by computing the standard pi-equivalent line injection at ``bus1`` from the converged ``v1``/``a1``/``v2``/``a2`` algebraic variables and the line's series + shunt admittances.
             */
            line_flows?: {
                [key: string]: components["schemas"]["LineFlow"];
            };
            /**
             * Generator Outputs
             * @description Per-generator P / Q output and terminal voltage, keyed by generator idx (stringified). Covers PV, Slack, GENROU, and GENCLS. Empty when PF did not converge.
             */
            generator_outputs?: {
                [key: string]: components["schemas"]["GeneratorOutput"];
            };
            /**
             * Load Consumption
             * @description Per-load P / Q consumption at the converged voltage, keyed by load idx (stringified). Covers PQ and ZIP. Empty when PF did not converge.
             */
            load_consumption?: {
                [key: string]: components["schemas"]["LoadConsumption"];
            };
        };
        /**
         * PflowRunRequest
         * @description Request body for ``POST /sessions/{id}/pflow``. Empty for v0.1; PF
         *     parameters are taken from the loaded case's defaults.
         */
        PflowRunRequest: Record<string, never>;
        /**
         * ProblemDetails
         * @description RFC 7807 problem-details object. Used for all 4xx and 5xx responses.
         */
        ProblemDetails: {
            /**
             * Type
             * @description URI reference identifying the problem type. ``about:blank`` means the title is the canonical reason for the status code.
             * @default about:blank
             */
            type: string;
            /**
             * Title
             * @description Short, human-readable summary of the problem.
             */
            title: string;
            /**
             * Status
             * @description HTTP status code for this response.
             */
            status: number;
            /**
             * Detail
             * @description Human-readable explanation specific to this occurrence of the problem (e.g., 'session id is required to be server-generated; remove the session_id field from your request body').
             */
            detail?: string | null;
            /**
             * Instance
             * @description URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionDescriptor
         * @description Response shape for session create / read.
         */
        SessionDescriptor: {
            /**
             * Session Id
             * @description Server-generated UUID-shaped opaque identifier for the session. Use it in subsequent URL paths (e.g., ``/sessions/{session_id}/case``).
             */
            session_id: string;
            /**
             * State
             * @description ``live`` if the worker subprocess is alive and accepting commands; ``closed`` if the session has been reaped or explicitly closed.
             * @enum {string}
             */
            state: "live" | "closed";
        };
        /**
         * SessionList
         * @description Response shape for ``GET /sessions``.
         */
        SessionList: {
            /**
             * Sessions
             * @description Snapshot of currently-active sessions for this token.
             */
            sessions: components["schemas"]["SessionDescriptor"][];
        };
        /**
         * SidecarLayout
         * @description Persisted SLD layout sidecar (one file per case).
         *
         *     Stored on disk as ``<case_path>.layout.json`` adjacent to the case file.
         *     The PUT endpoint validates this body, then writes atomically with mode
         *     0600.
         */
        SidecarLayout: {
            /**
             * Schema Version
             * @description Sidecar schema version (e.g., ``"1.0"``). Bumped on any incompatible shape change so the UI can fall back to defaults.
             */
            schema_version: string;
            /**
             * Andes Version
             * @description ANDES version the layout was saved against (e.g., ``"2.0.0"``). Recorded for diagnosis; not validated on read.
             */
            andes_version: string;
            /**
             * Coordinates
             * @description Per-bus coordinates, keyed by bus idx (stringified). Buses missing from this dict fall back to the renderer's auto-layout.
             */
            coordinates: {
                [key: string]: components["schemas"]["BusCoord"];
            };
            /**
             * Last Modified
             * @description ISO 8601 timestamp recorded by the client at save time. The server does NOT regenerate this on write; it stores the value the client sent so collaborative-edit conflict detection (a future feature) has a single source of truth.
             */
            last_modified: string;
        };
        /**
         * TdsBatchResult
         * @description Result of a batch TDS run (post-completion delivery).
         *
         *     Streaming TDS uses a different code path (Unit 6) that emits Arrow IPC
         *     frames per integration step. Batch mode blocks until completion and
         *     returns a summary; the per-step state values are NOT returned in batch
         *     mode (use streaming mode if you need them).
         */
        TdsBatchResult: {
            /**
             * Run Id
             * @description Server-generated identifier for this TDS run.
             */
            run_id: string;
            /**
             * Converged
             * @description ``true`` if TDS completed without becoming ``busted``. Numerical instability (e.g., a fault that doesn't clear) surfaces as ``converged: false`` with ``final_t`` < ``tf``.
             */
            converged: boolean;
            /**
             * Final T
             * @description Last simulation time reached, in seconds.
             */
            final_t: number;
            /**
             * Callpert Count
             * @description Number of times the per-step ``TDS.callpert`` hook fired during the run. Useful as a sanity check that streaming is wired.
             */
            callpert_count: number;
        };
        /**
         * TdsRunRequest
         * @description Request body for ``POST /sessions/{id}/tds`` (batch mode).
         *
         *     Streaming mode lands in Unit 6 and uses a separate ``?stream=ws`` query
         *     parameter; this schema is the batch-only surface for v0.1.
         */
        TdsRunRequest: {
            /**
             * Tf
             * @description Final simulation time, in seconds. Must be > 0.
             */
            tf: number;
            /**
             * H
             * @description Initial integration step size, in seconds. ``None`` lets ANDES use its case-default step size (typically 1/120 s).
             */
            h?: number | null;
        };
        /**
         * ToggleSpec
         * @description Status toggle on a device — used for line trips, generator trips, etc.
         *
         *     Maps to ``ss.add('Toggle', model=..., dev=..., t=...)``. Toggling sets the
         *     target device's status to its complement at time ``t`` (closed→open or
         *     open→closed).
         */
        ToggleSpec: {
            /**
             * Kind
             * @description Discriminator: this spec creates an ANDES Toggle device.
             * @default toggle
             * @constant
             */
            kind: "toggle";
            /**
             * Model
             * @description ANDES model class name whose device is being toggled. Examples: 'Line', 'GENROU', 'PV'.
             */
            model: string;
            /**
             * Dev Idx
             * @description ANDES idx of the device within ``model`` to toggle.
             */
            dev_idx: number | string;
            /**
             * T
             * @description Time the toggle fires, in seconds.
             */
            t: number;
        };
        /**
         * TopologyEntry
         * @description One element in a topology summary.
         */
        TopologyEntry: {
            /**
             * Idx
             * @description ANDES idx of the element (its public identifier in ANDES). Used as the stable handle in subsequent operations (e.g., Fault.bus references this idx).
             */
            idx: number | string;
            /**
             * Name
             * @description Human-readable name of the element.
             */
            name: string;
            /**
             * Kind
             * @description ANDES model class name (e.g., ``Bus``, ``Line``, ``GENROU``, ``PV``, ``Slack``, ``PQ``).
             */
            kind: string;
            /**
             * Params
             * @description Flat dict of model-input parameters for this element (e.g., for a Bus: ``Vn`` rated voltage in kV, ``vmax``/``vmin`` voltage limits, ``area``, ``zone``; for a Line: ``r``, ``x``, ``b``, ``g``, ``tap``, ``phi``; for a generator: ``Sn`` rated MVA, ``Vn``, ``bus``, plus model-specific params). The Inspector Properties tab in the v0.1 UI consumes this dict; absent params (None or unavailable on a given model) are omitted.
             */
            params?: {
                [key: string]: number | string | boolean;
            };
        };
        /**
         * TopologyParamMeta
         * @description One parameter row in a model's add/edit form schema.
         */
        TopologyParamMeta: {
            /**
             * Name
             * @description ANDES parameter name (e.g., ``Vn``).
             */
            name: string;
            /**
             * Kind
             * @description Form-input kind. ``string`` and ``number`` map to text/number inputs; ``bus_idx`` renders as a dropdown of existing buses; ``bool`` is a checkbox.
             * @enum {string}
             */
            kind: "string" | "number" | "bus_idx" | "bool";
            /**
             * Required
             * @description Whether the field is required when adding a new element. Optional fields collapse under the form's ``Show advanced`` disclosure.
             * @default false
             */
            required: boolean;
            /**
             * Unit
             * @description Display unit suffix (``kV``, ``pu``, ``MVA``, ``MWs/MVA``, ``rad``). Rendered inline next to numerical inputs.
             */
            unit?: string | null;
        };
        /**
         * TopologySchema
         * @description Per-model parameter metadata, used by the web client's polymorphic
         *     form generator (Unit 6).
         *
         *     Returned from ``GET /api/topology/schema``. Mirrors the wrapper-side
         *     ``_PARAMS_BY_MODEL`` table — adding a new model on the server
         *     automatically expands the form picker.
         */
        TopologySchema: {
            /**
             * Models
             * @description Mapping from ANDES model class name to ordered parameter metadata. Order is the rendering order in the form.
             */
            models: {
                [key: string]: components["schemas"]["TopologyParamMeta"][];
            };
        };
        /**
         * TopologySummary
         * @description Substrate's structural view of the loaded case.
         *
         *     ``state`` reflects whether ``ss.setup()`` has been committed. Some
         *     fields on individual elements are only populated after setup.
         */
        TopologySummary: {
            /**
             * State
             * @description ``pre-setup`` if disturbances can still be added; ``committed`` after PF or TDS has triggered ``ss.setup()``. Once committed, callers must POST /sessions/{id}/reload to add more disturbances.
             * @enum {string}
             */
            state: "pre-setup" | "committed";
            /**
             * Buses
             * @description Bus elements.
             */
            buses: components["schemas"]["TopologyEntry"][];
            /**
             * Lines
             * @description Line elements.
             */
            lines: components["schemas"]["TopologyEntry"][];
            /**
             * Transformers
             * @description Transformer elements split out from the ANDES ``Line`` bucket via the ``tap != 1.0 OR phi != 0.0`` heuristic. Pure transmission lines remain in ``lines``; off-nominal-tap and phase-shifting branches move here.
             */
            transformers: components["schemas"]["TopologyEntry"][];
            /**
             * Generators
             * @description Generator elements (PV, Slack, GENROU, GENCLS, etc.).
             */
            generators: components["schemas"]["TopologyEntry"][];
            /**
             * Loads
             * @description Load elements — both static (PQ) and dynamic (ZIP).
             */
            loads: components["schemas"]["TopologyEntry"][];
            /**
             * Shunts
             * @description Shunt elements (capacitors and reactors). Modeled as ANDES ``Shunt`` devices; rendered with the IEC 60617 shunt-cap or shunt-reactor icon depending on the sign of ``b``.
             */
            shunts?: components["schemas"]["TopologyEntry"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceFile
         * @description One entry in the workspace file lister response.
         */
        WorkspaceFile: {
            /**
             * Name
             * @description File name relative to the workspace root (no directory components in v0.1; the lister does not recurse).
             */
            name: string;
            /**
             * Size Bytes
             * @description File size in bytes as reported by ``os.stat``.
             */
            size_bytes: number;
            /**
             * Modified Iso
             * @description Last-modified time in ISO 8601 format with timezone (UTC). Computed from ``stat.st_mtime`` at list time.
             */
            modified_iso: string;
            /**
             * Format
             * @description Detected file format from the extension. Matches one of the ANDES-supported formats; non-matching files are excluded by the lister.
             * @enum {string}
             */
            format: "xlsx" | "raw" | "dyr" | "json" | "m";
        };
        /**
         * WorkspaceFileList
         * @description Response shape for ``GET /workspace/files``.
         */
        WorkspaceFileList: {
            /**
             * Files
             * @description Workspace files matching the supported extensions, sorted alphabetically by ``name``. Hidden files (dotfiles) and symlinks are excluded; subdirectories are not recursed in v0.1.
             */
            files: components["schemas"]["WorkspaceFile"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDescriptor"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Body included a client-supplied session_id (rejected). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description max_sessions cap reached; retry after closing a session. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDescriptor"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    closeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    loadCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadCaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySummary"];
                };
            };
            /** @description Workspace path validation failed (traversal, absolute path, NUL byte, missing). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES could not parse the case file. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTopology: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySummary"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or no case loaded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No case has been loaded into this session yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reloadCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySummary"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No case has been loaded into this session yet. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runPflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PflowRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PflowResult"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No case has been loaded into this session. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES setup() failed; call /reload to recover. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    addDisturbances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDisturbancesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddDisturbancesResponse"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session has already been committed (PF or TDS has run); call POST /api/sessions/{id}/reload to return to pre-setup. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES rejected one of the disturbance specs (e.g., bad bus idx). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTopologySchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologySchema"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    addElement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddElementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElementCreated"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session has already been committed (PF or TDS has run); call POST /api/sessions/{id}/reload to return to pre-setup. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request body exceeded the 65536-byte cap on topology mutation endpoints. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES rejected the add() call (unknown model, missing required param, invalid bus reference, etc.) or the wrapper-side whitelist found unknown param keys. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    editElement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                model: string;
                idx: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditElementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopologyEntry"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found, or no element of the given model+idx exists in the loaded System. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session has already been committed; call POST /api/sessions/{id}/reload to return to pre-setup. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Request body exceeded the 65536-byte cap on topology mutation endpoints. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES rejected the parameter write (e.g., unknown param key, wrong type, attempt to edit idx/name). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createBlankSystem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlankSystemResponse"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A System is already loaded on this session; reload or open a fresh session first. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runTds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TdsRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TdsBatchResult"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Session not found or already closed. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No case has been loaded into this session. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description ANDES setup() failed; call /reload to recover. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listWorkspaceFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceFileList"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getWorkspaceLayout: {
        parameters: {
            query: {
                /** @description Workspace-relative path of the case file the sidecar is paired with. The sidecar is read from ``<case_path>.layout.json``. */
                case_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SidecarLayout"];
                };
            };
            /** @description Workspace path validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sidecar not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Sidecar exists but does not match the SidecarLayout schema. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    putWorkspaceLayout: {
        parameters: {
            query: {
                /** @description Workspace-relative path of the case file the sidecar is paired with. The sidecar is written to ``<case_path>.layout.json``. */
                case_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SidecarLayout"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace path validation failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or invalid X-Andes-Token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Body exceeds the 256 KB sidecar cap. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Body did not validate against SidecarLayout. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
