"""Minimal PSS/E v33 ``.raw`` writer.

ANDES 2.0 ships a v33 reader (``andes.io.psse``) but no writer. This
module fills the gap for the v0.1.x save flow: when the user picks
``raw`` as the export format, the substrate calls ``write_raw(ss,
path)`` instead of ANDES's xlsx/json writers.

Coverage: the model classes the substrate's ``_PARAMS_BY_MODEL`` table
emits — Bus, PQ/ZIP→Load, Shunt→Fixed Shunt, PV/Slack/GENROU/GENCLS→
Generator, Line→Branch, Line+tap→Transformer (2W). 3W transformers,
DC lines, FACTS, switched shunts, and other PSS/E sections are emitted
as empty terminators (``0 / END OF X DATA, BEGIN Y DATA``) so the file
round-trips through ANDES's reader cleanly.

Sign / unit conventions match PSS/E v33:

- All P / Q values are MW / MVAr (not pu). The substrate converts ANDES
  pu values via ``ss.config.mva``.
- Bus voltage in pu, angle in DEGREES (not radians) — PSSE convention.
- Line R / X / B are in pu on system base.
- Transformer tap is on the wind-1 side (CW=1: pu off-nominal).

The output is plain text, no trailing whitespace per line. Each block
is terminated by ``0 / END OF <BLOCK> DATA, BEGIN <NEXT> DATA``. The
file ends with a single ``Q`` line per PSS/E convention.
"""

from __future__ import annotations

import logging
import math
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from andes.system import System

log = logging.getLogger("andes-app.psse_writer")


# ---- helpers ---------------------------------------------------------------


def _safe_list(model: Any, attr: str) -> list[Any]:
    """Read ``model.<attr>.v`` defensively. Returns [] on missing attr."""
    param = getattr(model, attr, None)
    if param is None:
        return []
    values = getattr(param, "v", None)
    if values is None:
        return []
    try:
        return list(values)
    except TypeError:
        return []


def _f(value: Any, default: float = 0.0) -> float:
    """Coerce to a finite float; fall back to ``default`` on NaN/Inf/None."""
    if value is None:
        return default
    try:
        f = float(value)
    except (TypeError, ValueError):
        return default
    if not math.isfinite(f):
        return default
    return f


def _qstr(value: Any, max_len: int = 12) -> str:
    """Quote a string for PSS/E: single quotes, padded to ``max_len``."""
    s = str(value) if value is not None else ""
    s = s[:max_len]
    return f"'{s:<{max_len}}'"


def _bus_int(idx: Any) -> int:
    """Coerce a bus idx to a PSS/E int. ANDES allows string idxs; PSS/E
    requires integers. We strip any non-digit prefix and parse the rest;
    if no digits remain, fall back to a hash-derived stable int.
    """
    s = str(idx)
    digits = "".join(c for c in s if c.isdigit())
    if digits:
        return int(digits)
    # Stable fallback for purely-string idxs.
    return abs(hash(s)) % (10**6)


# ---- block writers ---------------------------------------------------------


def _header(ss: System) -> list[str]:
    sbase = _f(getattr(ss.config, "mva", 100.0), 100.0)
    freq = _f(getattr(ss.config, "freq", 60.0), 60.0)
    return [
        f"0, {sbase:.2f}, 33, 0, 0, {freq:.2f}    / PSS/E v33 RAW (andes-app export)",
        "Generated by andes-app",
        "",
    ]


def _bus_block(ss: System) -> list[str]:
    lines: list[str] = []
    bus = getattr(ss, "Bus", None)
    if bus is None:
        return ["0 / END OF BUS DATA, BEGIN LOAD DATA"]
    idxs = _safe_list(bus, "idx")
    names = _safe_list(bus, "name")
    Vn = _safe_list(bus, "Vn")
    area = _safe_list(bus, "area")
    zone = _safe_list(bus, "zone")
    vmax = _safe_list(bus, "vmax")
    vmin = _safe_list(bus, "vmin")
    v = _safe_list(bus, "v")
    a = _safe_list(bus, "a")

    # Determine bus type by checking which generator buses exist.
    pv_buses = set()
    slack_buses = set()
    pv_model = getattr(ss, "PV", None)
    if pv_model is not None:
        for b in _safe_list(pv_model, "bus"):
            pv_buses.add(str(b))
    for gen_class in ("GENROU", "GENCLS"):
        m = getattr(ss, gen_class, None)
        if m is not None:
            for b in _safe_list(m, "bus"):
                pv_buses.add(str(b))
    slack_model = getattr(ss, "Slack", None)
    if slack_model is not None:
        for b in _safe_list(slack_model, "bus"):
            slack_buses.add(str(b))

    for i, idx in enumerate(idxs):
        i_int = _bus_int(idx)
        name = names[i] if i < len(names) else str(idx)
        baskv = _f(Vn[i], 100.0) if i < len(Vn) else 100.0
        # IDE: 1=PQ, 2=PV, 3=Slack, 4=isolated.
        if str(idx) in slack_buses:
            ide = 3
        elif str(idx) in pv_buses:
            ide = 2
        else:
            ide = 1
        ar = int(_f(area[i] if i < len(area) else 1, 1))
        zn = int(_f(zone[i] if i < len(zone) else 1, 1))
        vmag = _f(v[i] if i < len(v) else 1.0, 1.0)
        # PSSE uses degrees, ANDES stores radians.
        ang_deg = math.degrees(_f(a[i] if i < len(a) else 0.0, 0.0))
        nvhi = _f(vmax[i] if i < len(vmax) else 1.1, 1.1)
        nvlo = _f(vmin[i] if i < len(vmin) else 0.9, 0.9)
        lines.append(
            f"{i_int}, {_qstr(name)}, {baskv:.4f}, {ide}, "
            f"{ar}, {zn}, 1, {vmag:.5f}, {ang_deg:.5f}, "
            f"{nvhi:.5f}, {nvlo:.5f}, {nvhi:.5f}, {nvlo:.5f}"
        )
    lines.append("0 / END OF BUS DATA, BEGIN LOAD DATA")
    return lines


def _load_block(ss: System) -> list[str]:
    lines: list[str] = []
    mva_base = _f(getattr(ss.config, "mva", 100.0), 100.0)
    counter_per_bus: dict[int, int] = {}

    def _emit_load(model_name: str, p_attr: str, q_attr: str) -> None:
        m = getattr(ss, model_name, None)
        if m is None:
            return
        idxs = _safe_list(m, "idx")
        buses = _safe_list(m, "bus")
        ps = _safe_list(m, p_attr)
        qs = _safe_list(m, q_attr)
        for i in range(len(idxs)):
            bus = buses[i] if i < len(buses) else None
            if bus is None:
                continue
            i_int = _bus_int(bus)
            counter_per_bus[i_int] = counter_per_bus.get(i_int, 0) + 1
            load_id = f"{counter_per_bus[i_int]:>2}"  # PSSE uses 2-char id
            p_pu = _f(ps[i] if i < len(ps) else 0.0)
            q_pu = _f(qs[i] if i < len(qs) else 0.0)
            pl = p_pu * mva_base
            ql = q_pu * mva_base
            lines.append(
                f"{i_int}, '{load_id}', 1, 1, 1, "
                f"{pl:.5f}, {ql:.5f}, 0.0, 0.0, 0.0, 0.0, 1, 1, 0"
            )

    _emit_load("PQ", "p0", "q0")
    _emit_load("ZIP", "p0", "q0")
    lines.append("0 / END OF LOAD DATA, BEGIN FIXED SHUNT DATA")
    return lines


def _fshunt_block(ss: System) -> list[str]:
    lines: list[str] = []
    mva_base = _f(getattr(ss.config, "mva", 100.0), 100.0)
    counter_per_bus: dict[int, int] = {}
    m = getattr(ss, "Shunt", None)
    if m is not None:
        idxs = _safe_list(m, "idx")
        buses = _safe_list(m, "bus")
        gs = _safe_list(m, "g")
        bs = _safe_list(m, "b")
        for i in range(len(idxs)):
            bus = buses[i] if i < len(buses) else None
            if bus is None:
                continue
            i_int = _bus_int(bus)
            counter_per_bus[i_int] = counter_per_bus.get(i_int, 0) + 1
            shunt_id = f"{counter_per_bus[i_int]:>2}"
            g_pu = _f(gs[i] if i < len(gs) else 0.0)
            b_pu = _f(bs[i] if i < len(bs) else 0.0)
            gl = g_pu * mva_base
            bl = b_pu * mva_base
            lines.append(
                f"{i_int}, '{shunt_id}', 1, {gl:.5f}, {bl:.5f}"
            )
    lines.append("0 / END OF FIXED SHUNT DATA, BEGIN GENERATOR DATA")
    return lines


def _generator_block(ss: System) -> list[str]:
    lines: list[str] = []
    mva_base = _f(getattr(ss.config, "mva", 100.0), 100.0)
    counter_per_bus: dict[int, int] = {}

    def _emit_gen(model_name: str) -> None:
        m = getattr(ss, model_name, None)
        if m is None:
            return
        idxs = _safe_list(m, "idx")
        buses = _safe_list(m, "bus")
        Sn = _safe_list(m, "Sn")
        v0 = _safe_list(m, "v0")
        p0 = _safe_list(m, "p0")
        # Q values: ANDES has q0 on Slack but not PV; PV's Q is computed.
        # Use the post-PF q if available, else 0.
        qs = _safe_list(m, "q") or _safe_list(m, "q0")
        ps = _safe_list(m, "p") or _safe_list(m, "p0") or p0
        pmax = _safe_list(m, "pmax")
        pmin = _safe_list(m, "pmin")
        qmax = _safe_list(m, "qmax")
        qmin = _safe_list(m, "qmin")
        for i in range(len(idxs)):
            bus = buses[i] if i < len(buses) else None
            if bus is None:
                continue
            i_int = _bus_int(bus)
            counter_per_bus[i_int] = counter_per_bus.get(i_int, 0) + 1
            gen_id = f"{counter_per_bus[i_int]:>2}"
            mbase = _f(Sn[i] if i < len(Sn) else 100.0, 100.0)
            vs = _f(v0[i] if i < len(v0) else 1.0, 1.0)
            pg = _f(ps[i] if i < len(ps) else 0.0) * mva_base
            qg = _f(qs[i] if i < len(qs) else 0.0) * mva_base
            qt = _f(qmax[i] if i < len(qmax) else 9999.0, 9999.0) * mva_base
            qb = _f(qmin[i] if i < len(qmin) else -9999.0, -9999.0) * mva_base
            pt = _f(pmax[i] if i < len(pmax) else 9999.0, 9999.0) * mva_base
            pb = _f(pmin[i] if i < len(pmin) else 0.0, 0.0) * mva_base
            lines.append(
                f"{i_int}, '{gen_id}', "
                f"{pg:.5f}, {qg:.5f}, {qt:.5f}, {qb:.5f}, "
                f"{vs:.5f}, 0, {mbase:.4f}, "
                f"0.0, 1.0, 0.0, 0.0, 1.0, 1, 100.0, "
                f"{pt:.5f}, {pb:.5f}, "
                f"1, 1.0, 0, 1.0, 0, 1.0, 0, 1.0, 0, 1.0"
            )

    _emit_gen("PV")
    _emit_gen("Slack")
    _emit_gen("GENROU")
    _emit_gen("GENCLS")
    lines.append("0 / END OF GENERATOR DATA, BEGIN BRANCH DATA")
    return lines


def _branch_and_transformer_blocks(ss: System) -> tuple[list[str], list[str]]:
    """Walk Lines once; partition into branches (tap≈1, phi≈0) and 2W
    transformers. Returns (branch_lines, transformer_lines)."""
    branch_lines: list[str] = []
    trafo_lines: list[str] = []
    line_model = getattr(ss, "Line", None)
    if line_model is None:
        branch_lines.append("0 / END OF BRANCH DATA, BEGIN TRANSFORMER DATA")
        trafo_lines.append("0 / END OF TRANSFORMER DATA, BEGIN AREA DATA")
        return branch_lines, trafo_lines

    idxs = _safe_list(line_model, "idx")
    bus1 = _safe_list(line_model, "bus1")
    bus2 = _safe_list(line_model, "bus2")
    r = _safe_list(line_model, "r")
    x = _safe_list(line_model, "x")
    b = _safe_list(line_model, "b")
    g = _safe_list(line_model, "g")
    tap = _safe_list(line_model, "tap")
    phi = _safe_list(line_model, "phi")
    rate_a = _safe_list(line_model, "rate_a") or [0.0] * len(idxs)
    rate_b = _safe_list(line_model, "rate_b") or [0.0] * len(idxs)
    rate_c = _safe_list(line_model, "rate_c") or [0.0] * len(idxs)

    # Per (bus1, bus2) ckt counter.
    ckt_counter: dict[tuple[int, int], int] = {}

    for i in range(len(idxs)):
        b1_raw = bus1[i] if i < len(bus1) else None
        b2_raw = bus2[i] if i < len(bus2) else None
        if b1_raw is None or b2_raw is None:
            continue
        b1 = _bus_int(b1_raw)
        b2 = _bus_int(b2_raw)
        key = (b1, b2)
        ckt_counter[key] = ckt_counter.get(key, 0) + 1
        ckt = f"{ckt_counter[key]:>2}"

        ri = _f(r[i] if i < len(r) else 0.0)
        xi = _f(x[i] if i < len(x) else 0.0)
        bi = _f(b[i] if i < len(b) else 0.0)
        gi = _f(g[i] if i < len(g) else 0.0)
        tap_i = _f(tap[i] if i < len(tap) else 1.0, 1.0)
        phi_i_rad = _f(phi[i] if i < len(phi) else 0.0)
        ratea = _f(rate_a[i] if i < len(rate_a) else 0.0)
        rateb = _f(rate_b[i] if i < len(rate_b) else 0.0)
        ratec = _f(rate_c[i] if i < len(rate_c) else 0.0)

        is_trafo = abs(tap_i - 1.0) > 1e-9 or abs(phi_i_rad) > 1e-9
        if is_trafo:
            # 4-line PSSE 2W transformer record.
            phi_deg = math.degrees(phi_i_rad)
            trafo_lines.append(
                f"{b1}, {b2}, 0, '{ckt}', 1, 1, 1, 0.0, 0.0, "
                f"2, {_qstr('ANDES_TRAFO')}, 1, "
                f"1, 1.0, 0, 1.0, 0, 1.0, 0, 1.0, "
                f"''"
            )
            trafo_lines.append(
                f"{ri:.5f}, {xi:.5f}, 100.00"
            )
            trafo_lines.append(
                f"{tap_i:.5f}, 0.000, {phi_deg:.5f}, "
                f"{ratea:.2f}, {rateb:.2f}, {ratec:.2f}, "
                f"0, 0, 1.10000, 0.90000, 1.10000, 0.90000, 33, 0, 0.0, 0.0, 0.0"
            )
            trafo_lines.append("1.00000, 0.000")
        else:
            # Branch record.
            branch_lines.append(
                f"{b1}, {b2}, '{ckt}', "
                f"{ri:.5f}, {xi:.5f}, {bi:.5f}, "
                f"{ratea:.2f}, {rateb:.2f}, {ratec:.2f}, "
                f"{gi:.5f}, 0.00000, 0.00000, 0.00000, "
                f"1, 1, 0.0, "
                f"1, 1.0, 0, 1.0, 0, 1.0, 0, 1.0"
            )

    branch_lines.append("0 / END OF BRANCH DATA, BEGIN TRANSFORMER DATA")
    trafo_lines.append("0 / END OF TRANSFORMER DATA, BEGIN AREA DATA")
    return branch_lines, trafo_lines


def _empty_terminators() -> list[str]:
    """Empty section terminators after Transformer up through GNE."""
    return [
        "0 / END OF AREA DATA, BEGIN TWO-TERMINAL DC DATA",
        "0 / END OF TWO-TERMINAL DC DATA, BEGIN VSC DC LINE DATA",
        "0 / END OF VSC DC LINE DATA, BEGIN IMPEDANCE CORRECTION TABLE DATA",
        "0 / END OF IMPEDANCE CORRECTION TABLE DATA, BEGIN MULTI-TERMINAL DC DATA",
        "0 / END OF MULTI-TERMINAL DC DATA, BEGIN MULTI-SECTION LINE DATA",
        "0 / END OF MULTI-SECTION LINE DATA, BEGIN ZONE DATA",
        "0 / END OF ZONE DATA, BEGIN INTER-AREA TRANSFER DATA",
        "0 / END OF INTER-AREA TRANSFER DATA, BEGIN OWNER DATA",
        "0 / END OF OWNER DATA, BEGIN FACTS DEVICE DATA",
        "0 / END OF FACTS DEVICE DATA, BEGIN SWITCHED SHUNT DATA",
        "0 / END OF SWITCHED SHUNT DATA, BEGIN GNE DATA",
        "0 / END OF GNE DATA, BEGIN INDUCTION MACHINE DATA",
        "0 / END OF INDUCTION MACHINE DATA",
        "Q",
    ]


# ---- entry point -----------------------------------------------------------


def write_raw(ss: System, path: str | Path) -> Path:
    """Write the System to a PSS/E v33 raw file at ``path``.

    Raises ``OSError`` if the file can't be written. The caller (the
    save_case wrapper method) is responsible for canonicalizing the
    target path through ``open_workspace_file_for_write``.
    """
    target = Path(path)
    output: list[str] = []
    output.extend(_header(ss))
    output.extend(_bus_block(ss))
    output.extend(_load_block(ss))
    output.extend(_fshunt_block(ss))
    output.extend(_generator_block(ss))
    branch_lines, trafo_lines = _branch_and_transformer_blocks(ss)
    output.extend(branch_lines)
    output.extend(trafo_lines)
    output.extend(_empty_terminators())
    target.write_text("\n".join(output) + "\n")
    log.info("wrote PSS/E v33 raw file: %s (%d lines)", target, len(output))
    return target
